import "./core/alignment-parameters.test.mjs";
import "./core/bit-matrix.test.mjs";
import "./core/bit-stream.test.mjs";
import "./core/gf256.test.mjs";
import "./core/function-information.test.mjs";
import "./core/masks.test.mjs";
import "./core/modes.test.mjs";
import "./core/reed-solomon.test.mjs";
import "./core/version.test.mjs";
